namespace LiveMonitor {
	export enum CircuitStatus {
		ENABLED = 0,
		DISABLED,
		SHUTDOWN,
		RESERVED,
		OUT_OF_SERVICE
	}

	export enum CallStatus {
		ON,
		OFF,
		BLOCKED,
		NOT_RECORDED
	}

	export enum CtrlMsgType {
		WM_CTRL_MSG_RANGE_BEGIN = 2024,
		WM_CTRL_MSG_FIRE_EVENT,
		WM_CTRL_MSG_DISCONNECT,
		WM_CTRL_MSG_CONNECT,
		WM_CTRL_MSG_REGISTER,
		WM_CTRL_MSG_UNREGISTER,
		WM_CTRL_MSG_LICENSE_LOGON,
		WM_CTRL_MSG_LICENSE_LOGOFF,
		WM_CTRL_MSG_EVENT_DISCONNECTED,
		WM_CTRL_MSG_EVENT_CONNECTED,
		WM_CTRL_MSG_EVENT_REGISTERED,
		WM_CTRL_MSG_EVENT_UNREGISTERED,
		WM_CTRL_MSG_LICENSE_LOGGED_ON,
		WM_CTRL_MSG_LICENSE_LOGGED_OFF,
		WM_CTRL_MSG_EVENT_CALLSTART, //2038
		WM_CTRL_MSG_EVENT_CALLEND, //2039
		WM_CTRL_MSG_EVENT_CALLBLOCK,
		WM_CTRL_MSG_START_MONITOR,
		WM_CTRL_MSG_END_MONITOR,
		WM_CTRL_MSG_STARTED_MONITOR,
		WM_CTRL_MSG_ENDED_MONITOR,
		WM_CTRL_MSG_PAUSED_MONITOR,
		WM_CTRL_MSG_RESUMED_MONITOR,
		WM_CTRL_MSG_SECURITY_LOGGED_ON,
		WM_CTRL_MSG_SECURITY_LOGGED_OFF,
		WM_CTRL_MSG_RANGE_END,
		WM_CTRL_MSG_START_REMOTE_MONITOR,
		WM_CTRL_MSG_STARTED_REMOTE_MONITOR,
		WM_CTRL_MSG_SEND_ALARM
	}

	export enum DeviceType {
		ANY = 0,
		PHONE,
		VISITOR_VIDEO,
		INMATE_VIDEO,
		PAYMENT_KIOSK
	}

	export enum SignalRConnectionState {
		CONNECTING = 0,
		CONNECTED,
		RECONNECTING,
		DISCONNECTED
	}
}